version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - if [ $CPU_ONLY ]; then $DOCKERFILE_PATH="Dockerfile"; else $DOCKERFILE_PATH="Dockerfile-CPU"; fi
      
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`

      - echo Building main docker image
      - docker build -t $MAIN_REPOSITORY_URI:$IMAGE_TAG -f $DOCKERFILE_PATH .
      - docker tag $MAIN_REPOSITORY_URI:$IMAGE_TAG $MAIN_REPOSITORY_URI:latest

      - cd planercnn
      - echo Building planes docker image
      - docker build -t $PLANES_REPOSITORY_URI:$IMAGE_TAG -f $DOCKERFILE_PATH .
      - docker tag $PLANES_REPOSITORY_URI:$IMAGE_TAG $PLANES_REPOSITORY_URI:latest
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`

      - python3 writeartifacts.py $CODEBUILD_SRC_DIR/imagedefinitions.json $MAIN_REPOSITORY_URI:$IMAGE_TAG

      - echo Pushing main docker image
      - docker push $MAIN_REPOSITORY_URI:latest
      - docker push $MAIN_REPOSITORY_URI:$IMAGE_TAG

      - echo Pushing planes docker image
      - docker push $PLANES_REPOSITORY_URI:latest
      - docker push $PLANES_REPOSITORY_URI:$IMAGE_TAG
artifacts:
  name: ECSImageDefinitions
  base-directory: $CODEBUILD_SRC_DIR
  files:
    - imagedefinitions.json
