
REGISTRY=312943975091.dkr.ecr.us-east-1.amazonaws.com
REPO=cb-imageprocessingservice-api-4  
LABEL=${REGISTRY}/${REPO}:latest
BUILD_FILE=pipeline/config.py

#increment BUILD_NUMBER
awk -F '= ' '/BUILD_NUMBER \=/{$2=$2+1" #Generated by deploy.sh"}1' OFS='= ' ${BUILD_FILE} > ${BUILD_FILE}.tmp && mv ${BUILD_FILE}.tmp ${BUILD_FILE}

aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${REGISTRY}

docker build -t ${REPO} .

docker tag ${REPO}:latest ${LABEL}

docker push ${LABEL}