from abc import abstractmethod
import typing
from enum import IntEnum
from types import SimpleNamespace
from pipeline.data.surface_type import SurfaceType

BUILD_NUMBER = 1007 #Generated by deploy.sh

class PipelineMode(IntEnum):
    Serve = 0
    Process = 1
    Restore = 2

class PipelineConfig(SimpleNamespace):
    mode:PipelineMode = PipelineMode.Serve
    api_level=4
    minor_version_string = "0.2"

    api_version_string = "%d.%s" % (api_level, minor_version_string)
    api_long_version_string = "%s.%d" % (api_version_string, BUILD_NUMBER)

    use_gpu=True
    batch_max_wait_time=1.0
    batch_debounce_time=0.2
    batch_max_size=1

    src_path=None
    dest_path=None

    sqs_queue_name=None
    session_config=None

    model_path="tensorflow_models"
    semantic_model_path="gluon_models"
    fov_model_path = "sklearn_models/fov_classifier_lc128.joblib"
    hed_model_path = "hed_model/HED_pretrained_bsds.npz"
    planes_url="http://localhost:8081/"

    multi_mask=True
    surface_type_whitelist = [SurfaceType.Floor, SurfaceType.Ceiling, SurfaceType.Wall]

    restore_step=None
    export_step=None
    stop_step=None

    logging_dir="logging"
    logging_level=0
    logging_step = None

    cpu_networks_port=8082
    cpu_networks_script="runcpunetworks.py"
    cpu_networks_allotted_failures=0
    cpu_networks_show_stderr=True
    cpu_networks_healthchecker_interval=5
    
    @property
    def cpu_networks_path(self) -> str:
        return "http://localhost:%d" % self.cpu_networks_port
